appname = casdoor
httpport = 8000
runmode = dev
copyrequestbody = true
driverName = postgres
dataSourceName = user=postgres password=casdoor host=casdoor-postgres port=5432 sslmode=disable dbname=casdoor
dbName = casdoor
showSql = false
origin = http://localhost:8000
staticBaseUrl = "https://cdn.casbin.org"
defaultLanguage = "en"
initDataNewOnly = true
initDataFile = "/init_data.json"
logConfig = {"adapter":"file", "filename": "logs/casdoor.log", "maxdays":30, "perm":"0770"}
